[package]
name = "turse-macro"
version = "0.1.1"
edition = "2024"
description = "trs! macro for turse"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = "2.0.115"
turse-core = "0.1.1"
